$(document).ready(function(){
    $(".design").click(function(){
        $("#hide1").slideToggle();
        $("#design1").slideToggle();
    });
    $(".development").click(function(){
        $("#hide2").slideToggle();
        $("#design2").slideToggle();
    })
    $(".product").click(function(){
        $("#hide3").slideToggle();
        $("#design3").slideToggle();
    })
    $('#project1').hide();
    $('.port').hover(function(){
        $(this).find('#project1').toggle(500);
    });
});